#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Mu4e  | Deerpig's Dot Emacs
#+AUTHOR: Brad Collins
#+EMAIL: brad@chenla.la
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: header-args    :results drawer  :tangle emacs-mu4e.el
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/deerpig/dot-emacs/dot-mu4e.org
:Created:   2017-07-02T18:04@Prek Leap (11.642600N-104.919210W)
:ID:        c99bb7c0-a0e5-4422-9eca-6fe454c91ea1
:VER:       552265552.745265710
:GEO:       48P-491193-1287029-15
:BXID:      pig:SQC5-4643
:Class:     dotemacs
:Type:      literate-program
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:

[[https://img.shields.io/badge/made%20by-Deerpig-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-dotemacs-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/type-literate%20program-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction

  - [[http://www.djcbsoftware.nl/code/mu/mu4e.html][Mu4e]] | djcbsoftware
  - [[http://irreal.org/blog/?p=4807][Mu4e and Org Mode]] | Irreal
  - [[http://pragmaticemacs.com/emacs/master-your-inbox-with-mu4e-and-org-mode/][Master your inbox with mu4e and org-mode]] | Pragmatic Emacs
  - [[http://cachestocaches.com/2017/3/complete-guide-email-emacs-using-mu-and-/][A Complete Guide to Email in Emacs using Mu and Mu4e]]

* Mu4e Config
** File Header

#+begin_src emacs-lisp
;; -*- mode: EMACS-LISP; fill-column: 75; comment-column: 50; -*-
;; Emacs Mu4e Configuration

#+end_src

** Mu4e Package

Follow instructions to download and install the /mu/ search engine which
is bundled with /mu4e/:

  [[http://www.djcbsoftware.nl/code/mu/mu4e/Installation.html][Mu4e 0.9.18 user manual: Installation]]

You will need to install an app to synchronize imap mailboxes.  We're
using [[https://sourceforge.net/p/isync/isync/ci/master/tree/][mbsync]] but many people use /offlineIMAP/ and I used fetchmail
for many years without complaint.

#+begin_src emacs-lisp

;; mu4e ===========================================

;; the exact path may differ -- check it
(add-to-list 'load-path "/usr/local/share/emacs/site-lisp/mu4e")
(require 'mu4e)
(require 'org-mu4e)

#+end_src

Set application names.

When running mbsync, run it quietly so that we don't see it pop up
every ten minutes in a new buffer.

#+begin_src emacs-lisp
(setq mu4e-get-mail-command "mbsync -aqV"
      mu4e-mu-binary (executable-find "mu"))

#+end_src

Set directory name for attachments.

#+begin_src emacs-lisp
(setq mu4e-attachment-dir  "~/Downloads")

#+end_src

Set Names and email addresses.

#+begin_src emacs-lisp
(setq mu4e-user-mail-address-list
      '("brad@chenla.la"
	    "deerpig@gmail.com"
	    "brad.collins@pathmazing.com")
      ;; emacs email defaults
      user-full-name    "Brad Collins"
      user-mail-address "brad@chenla.la"
      mail-host-address "chenla.la")

#+end_src

Misc settings.

#+begin_src emacs-lisp
(setq ;;mu4e-sent-messages-behavior 'delete
      ;; don't show info about indexing new messages
      mu4e-hide-index-messages t
      ;; attempt to show images
      mu4e-view-show-images t
      mu4e-view-image-max-width 800
      ;; start in non-queuing mode
)

#+end_src

Set up outgoing mail using /ssmtp/.

#+begin_src emacs-lisp
(setq smtpmail-queue-mail nil
      smtpmail-queue-dir "~/Maildir/queue/"
      message-kill-buffer-on-exit t ;; kill sent msg buffers
      ;; use ssmtp
      message-send-mail-function 'message-send-mail-with-sendmail
      sendmail-program (executable-find "/usr/sbin/ssmtp")
      ;; Look at the from header to determine the account from which
      ;; to send. Might not be needed b/c of mlh-msmtp
      ;;mail-specify-envelope-from t
      ;;mail-envelope-from 'header
      ;;message-sendmail-envelope-from 'header
)

#+end_src

Check for new mail every 30 minutes.  I would like to check more
often, but even when running asynchronously, it still slows things
down.

#+begin_src emacs-lisp 
;; check mail every 30 minutes
;;(setq
;; mu4e-change-filenames-when-moving t
;; mu4e-update-interval 1800)
#+end_src


# Notifications

Use mu4e-alert together with the external package notify-send to pop
up notifications on the desktop.  You get a nice little envelope icon
in the mode-line and an unread email count.

 - [[https://github.com/iqbalansari/mu4e-alert]]

#+begin_src emacs-lisp

;; me4e-alert ----------------------------------------------

(use-package mu4e-alert
  :ensure t
  :config
  (mu4e-alert-enable-notifications)
  (mu4e-alert-set-default-style 'libnotify)
  (setq mu4e-alert-interesting-mail-query
        (concat "(maildir:/chenla/INBOX AND date:today..now"
                " OR maildir:/gmail/INBOX AND date:today..now"
                " AND flag:unread"))

  (alert-add-rule
   :category "mu4e-alert"
   :predicate (lambda (_) (string-match-p "^mu4e-" (symbol-name major-mode)))
   :continue t)

  ;; display stuff on modeline as well as notify
  (add-hook 'after-init-hook #'mu4e-alert-enable-notifications)
  (add-hook 'after-init-hook #'mu4e-alert-enable-mode-line-display)
  )
#+end_src

Set a couple of keybindings:

Open URLs in the default external browser by hitting <return> when the
point is on a link.

#+begin_src emacs-lisp
;; <RET> Opens URLs in external browsers
(define-key mu4e-view-mode-map (kbd "RET") 'mu4e~view-browse-url-from-binding)
#+end_src

org-store-link creates an org link to the email in view mode
but I find the default (C-c M-s) to be awkward and difficult
to remember.  In mu4e, bind it to 'l' which matches what I
am using in elfeed.

I suppose we could try to do something similar to
elfeed-show-link title so the link is in the clipboard, so
you don't have to remember C-c C-l to paste the link.

#+begin_src emacs-lisp
;; re-map org-store-link to match command used in elfeed.
(define-key mu4e-view-mode-map (kbd "l") 'org-store-link)
#+end_src



Now set up the bookmarks that are shown on the main screen:

#+begin_src emacs-lisp
;; The bookmarks for the main screen
(setq mu4e-bookmarks
          `(;;(,(mlh-mu4e-unread-mail-query) "New messages"         ?b)
            ;;("maildir:/elastic/build"      "Build failures"       ?B) 
           ("date:today..now NOT T"       "Today's messages"     ?t)
            ("date:7d..now NOT T"          "Last 7 days"          ?w)
            ("maildir:/chenla/INBOX"       "Chenla"               ?c)
            ("maildir:/gmail/INBOX"        "Deerpig"              ?d)
            ("maildir:/cas/github"         "Casnak"               ?n)
          ;;  ("maildir:/path/INBOX"         "Pathmazing"           ?p)
            ("maildir:/chenla/INBOX OR maildir:/gmail/INBOX OR maildir:/path/INBOX"
             "All Mail" ?a)))

#+end_src

Finally set up sig files.

#+begin_src emacs-lisp
;; if you set this to nil so signature is not included by default
;; you can include in message with C-c C-w
(setq mu4e-compose-signature-auto-include t)
(setq mu4e-compose-signature (with-temp-buffer
			       (insert-file-contents "~/.dotfiles/signature")
			       (buffer-string)))
;; message-signature-file NOT used by mu4e
(setq message-signature-file "~/.dotfiles/signature")

#+end_src

Load mu4e when emacs starts up.

Commented out for now.  Email is already being checked and downloaded,
so not sure why do we need to start mu4e as well?  I don't mind typing
M-x mu4e and there are many times I want to run emacs but not mu4e.

#+begin_src emacs-lisp
;;(mu4e t)
#+end_src
