#+TITLE:Dot Emacs: Dot Emacs
#+AUTHOR: Brad Collins
#+EMAIL: brad@chenla.la
#+PROPERTY: header-args    :results drawer  :tangle emacs-helm.el

* Introduction

#+begin_quote
"Pray!"

/Recruits/: [chanting] "This is my rifle. There are many others like it,
but this one is mine. My rifle is my best friend. It is my life. I
must master it as I must master my life. Without me, my rifle is
useless. Without my rifle, I am useless. I must fire my rifle true. I
must shoot straighter than my enemy, who is trying to kill me. I must
shoot him before he shoots me. I will. Before God I swear this creed:
my rifle and myself are defenders of my country, we are the masters of
our enemy, we are the saviors of my life. So be it, until there is no
enemy, but peace. Amen."

-- Rifleman's Creed
   Full Metal Jacket | 1987
   [[https://www.youtube.com/watch?v=Hgd2F2QNfEE][Rifleman's Creed]]  | YouTube

Now write some elisp code that replaces 

  - "rifle"        with "emacs"
  - "God"          with "Root"
  - "fire"         with "execute"
  - "shoot"        with "code"
  - "country"      with "open source software"
  - "our enemy"    with "this universe, the wind of time is flowing
                         relative to me, it's all a figment of my mind"
  - "shoot him"    with "commit my code first so"
  - "he shoots me" with "others can work on more interesting problems"
  - "peace"        with "Microsoft and Oracle"
  - the Emacs Hacker's Creed

#+end_quote

The quotes from /Full Metal Jacket/ are only half in jest.  The
recruits are trained with M1 Carbines.  These are single shot
(they have a magazine? so what do you call them) rifles.  They are
bog standard rifles  -- learn the basics, then use M-16s in the field.

The M1 is bog standard emacs, start with that, learn that, master
that.  Learn to pull it apart, and put it back together again with
your eyes closed.  Teach your fingers to do things the same as you
touch type -- without thinking, committing the basics to muscle memory.

Why? because there will be countless times when you use emacs without
all the fancy-ass customizations you've made.  When you are ssh'd into
a remote computer, when you are logged in as root on a computer you
forgot to put your init on, when you've done something dumb and
screwed up your init file and you are dropped back into vanilla emacs
with a white background with the splash screen and menus and the ugly
tool bar until you can debug whatever you screwed up before you can
get back your evil-mode key-bindings and the illusion that you are
using /spacemacs/ instead of a heavily pre-tweaked emacs that emulates
Vim.  You should be as fluid in standard emacs as you are in your
custom environment.  You don't need a mouse, or menus or scrollbars or
even font-locking (colours).  A master customizes his tools and work
environment to suit her workflow, but can work just as well without
them.  All you need is emacs.

What I did was force myself to use emacs in a shell on a remote
computer for the first month.  No mouse, no fancy init -- everything
out of the box until I understood better what I was doing.  You end up
customizing stuff within a day or so, but nothing crazy.

   then

Come back here and look at what I've got -- this is the M-16 version,
it's higher powered, but it can be finicky and unreliable unless you
know what you're doing.  (yeah yeah I know, I'm beginning to streach this
metaphor a bit thin).

You /can/ use the M16 first, but you will be better off if you master
the M1 before you take on the high powered stuff.


#+begin_quote
This is my rifle!
This is my gun!

This is for fighting!
This is for fun!

-- Full Metal Jacket | 1987
   [[https://www.youtube.com/watch?v=4kU0XCVey_U][This Is My Rifle. This Is My Gun]] | YouTube
#+end_quote


* Header

#+begin_src emacs-lisp
;; Deerpig's Crufty .emacs
;; This dot emacs is a poor example 

#+end_src

* External Paths

#+begin_src emacs-lisp

;; External path search ====================================

(add-to-list 'load-path "~/emacs-lisp")
(add-to-list 'load-path "~/emacs-lisp/test")
(add-to-list 'load-path "~/emacs-lisp/emacs-wiki-deerpig")
(add-to-list 'load-path "~/emacs-lisp/docs")
(add-to-list 'load-path "~/emacs-lisp/uri")
(add-to-list 'load-path "~/emacs-lisp/remember")
(add-to-list 'load-path "~/emacs-lisp/psgml")
(add-to-list 'load-path "~/emacs-lisp/ecb")
(add-to-list 'load-path "~/emacs-lisp/semantic")
(add-to-list 'load-path "~/emacs-lisp/tex")
(add-to-list 'load-path "~/emacs-lisp/ses")
(add-to-list 'load-path "~/emacs-lisp/burr")
(add-to-list 'load-path "~/emacs-lisp/sxml-mode")
(add-to-list 'load-path "~/emacs-lisp/xpath")

(add-to-list 'load-path (expand-file-name "~/emacs-lisp/w3/lisp"))
(add-to-list 'load-path "~/emacs-lisp/elib-1.0")
(add-to-list 'load-path "~/emacs-lisp/regexp-info")
(add-to-list 'load-path "~/emacs-lisp/edb")
(add-to-list 'load-path "~/emacs-lisp/xtla")
(add-to-list 'load-path "~/emacs-lisp/wl/elmo")
(add-to-list 'load-path "~/emacs-lisp/etask")
(add-to-list 'load-path "~/emacs-lisp/burs")
(add-to-list 'load-path "~/emacs-lisp/atom-blogger")

(add-to-list 'load-path "~/emacs-lisp/emacs-atom-api")
(add-to-list 'load-path "~/emacs-lisp/nxhtml")
(add-to-list 'load-path "~/emacs-lisp/hyperbole")
(add-to-list 'load-path "~/emacs-lisp/emacs-jabber")
(add-to-list 'load-path "~/emacs-lisp/jd-el")
(add-to-list 'load-path "~/emacs-lisp/google-contacts")
(add-to-list 'load-path "~/emacs-lisp/multiple-cursors.el")
(add-to-list 'load-path "~/emacs-lisp/emacs-async")


#+end_src

* Default Font

#+begin_src emacs-lisp
;; set the default font ====================================

(set-default-font "Deja Vu Sans Mono-12")
 ;;(set-fontset-font (frame-parameter nil 'font)
 ;;   'han '("cwTeXHeiBold" . "unicode-bmp"))
#+end_src

* Package & Melpa

#+begin_src emacs-lisp

;; Package Manager & Repositories ==========================
(eval-when-compile
  (require 'package))
(setq package-enable-at-startup nil)
(add-to-list 'package-archives
	     '("melpa" . "https://melpa.org/packages/"))

(package-initialize)
#+end_src

* Customizations

Emacs has a bit of an annoying habit of adding things to your init
file without telling you.  This becomes a problem when you keep your
init file in version control and then use the init file for multiple
machines.  Most of the time this is an inconvienence because you are
having to commit things that emacs has added, not you.  But it also
can be a pain-in-the-ass when it causes commit conflicts.

So keep customize stuff in it's own file and then add that file to git
ignore.

#+begin_src emacs-lisp

;; Customizations ==========================================
;; keep all emacs customizations in file that is not
;; part of the repo.
(setq custom-file "~/.emacs-custom")
(load custom-file 'noerror)

#+end_src

* Private

Like in customize, we need to keep things like passwords and API keys
out of the main init file which is in a public github repo.

The solution is to encrypt the file using gpg.

* Load Init Files

At the moment we are still loading tangled files.

#+begin_src emacs-lisp

;; Load literate Org files =================================

(load "~/.emacs-user-info")
(load "~/.emacs-helm")
(load "~/.emacs-packages")
(load "~/.emacs-hydra")
(load "~/.emacs-mu4e")
(load "~/.emacs-org")

#+end_src


* Browse Url Applications

Open *EVERYTHING* in firefox.

with attitide....

#+begin_src emacs-lisp
(defvar browse-url-firefox-program 'firefox)
(defvar browse-url-kde-program 'firefox)
(defvar browse-url-gnome-moz-program 'firefox)
(defvar browse-url-mozilla-program 'firefox)
(defvar browse-url-galeon-program 'firefox)
(defvar browse-url-netscape-program 'firefox)
(defvar browse-url-mosaic-program 'firefox)
(defvar browse-url-xterm-program 'firefox)

#+end_src

* Browse Apropos 

At the moment I don't have any of these bound to any keys, I've been
using helm's surfraw integration.

But I'm not giving up -- I may yet find a way of working it into my
workflow.

#+begin_src emacs-lisp

;; Browse Apropos URL ======================================

(require 'browse-apropos-url)
(provide 'browse-url)
(require 'thingatpt+)

;; Choose commands that mirror DuckDuckGo !bang commands when
;; possible.  !bang should go to search on a site.  !!bangbang should
;; just be a shortcut to a url.  If it's not a search link, default
;; both single and double bang prefix to home page.

(setq apropos-url-alist
      '( ;; DuckDuckGo is default search engine.
	("^\??:? +\\(.*\\)" .       ;; "?" defaults to DuckDuckGo
	 "http://duckduckgo.com/?q=\\1")
	("^!ddg?:? +\\(.*\\)" .     ;; DuckDuckGo Search
	 "http://duckduckgo.com/?q=\\1")
        ("^!!ddg"                   ;; DuckDuckGo Home Page
	 "http://duckduckgo.com")
	("^!bang$" .                ;; DuckDuckGo !bang Page
	 "http://duckduckgo.com/bang.html")
        ;; Google Sites ;;;;;;;;;;;;;;;;;;;;;;
	("^gw?:? +\\(.*\\)" .
         "http://www.google.com/search?q=\\1")
	("^!g?:? +\\(.*\\)" . 	    ;; Google Web Search
	 "http://www.google.com/search?q=\\1")
        ("^!!g$" . 	            ;; Google Home Page
	 "http://google.com/")
        ("^!reader?:? +\\(.*\\)" .  ;; Search Google Reader
         "http://www.google.com/reader/view/#search/\\1")
        ("^!!reader$" .             ;; Google Reader Home
         "http://reader.google.com/")
        ("^!!voice$" .              ;; Google Voice
         "http://voice.google.com/")
	("^!!gmail$" .              ;; GMail
	 "http://mail.google.com/")
	("^!gi:? +\\(.*\\)" .       ;; Google Images
	 "http://images.google.com/images?sa=N&tab=wi&q=\\1")
	("^!!gi$" .                 ;; Google Images
	 "http://images.google.com/")
	("^!gg:? +\\(.*\\)" .       ;; Google Groups
	 "http://groups.google.com/groups?q=\\1")
        ("^!gn:? +\\(.*\\)" .       ;; Google News Search
         "http://news.google.com/news?sa=N&tab=dn&q=\\1")
        ("^!!gn$" .                 ;; Google News Home
         "http://news.google.com/")
	;;Blekko ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
        ("^!blekko?:? +\\(.*\\)" .  ;; Blekko Search
	 "http://blekko.com/ws/+\\1")
	("^!!blekko$" .             ;; Blekko Home
	 "http://blekko.com/")
        ;; Tech News ;;;;;;;;;;;;;;;;;;;;;;;;;;
	("^!/\.$" . ;; Slashdot Home
         "http://www.slashdot.org")
	("^!!/\.$" . ;; Slashdot Home
         "http://www.slashdot.org")
        ("^!bb$" . ;; Boing Boing Home
         "http://boingboing.net")
        ("^!!bb$" . ;; Boing Boing Home
         "http://boingboing.net")
        ;; Emacs ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
	("^!emacs:? +\\(.*\\)" . ;; Emacs Wiki Search
         "http://www.emacswiki.org/cgi-bin/wiki?search=\\1")
        ("^!!emacs$" . ;; Emacs Wiki Home
         "http://www.emacswiki.org")
        ;;Hacker News ;;;;;;;;;;;;;;;;;;;;;;;;
	("^!hn:? +\\(.*\\)" . ;; Hacker News Search
	"http://www.hnsearch.com/search#request/all&q=\\1")
	("^!!hn$" . ;; Hacker News Home
	"http://news.ycombinator.com")
	;;Torrent Search ;;;;;;;;;;;;;;;;;;;;
	("^!tpb:? +\\(.*\\)" . ;;The Pirate Bay
	"http://thepiratebay.com/search/\\1")
	("^!demon:? +\\(.*\\)" . ;; Demonoid Search
	"https://www.demonoid.me/files/?query=\\1" )
	("^!demonoid:? +\\(.*\\)" . ;; Demonoid Search
	"https://www.demonoid.me/files/?query=\\1" )
	("^!isohunt:? +\\(.*\\)" . ;;ISOHunt
	"https://isohunt.com/torrents/?ihq=\\1" )
	("^!cheggit:? +\\(.*\\)" . ;;Cheggit Search
	"http://cheggit.net/browsetorrents.php?filter=all%3A%5B\\1" )
	("^!!cheggit:? +\\(.*\\)" . ;;Cheggit Home
	"http://cheggit.net/browsetorrents.php" )
	("^!jpop:? +\\(.*\\)" . ;; JPopSuki Artist Search
	"http://jpopsuki.eu/torrents.php?action=advanced&artistname=\\1" )
	;; Content Companies ;;;;;;;;;;;;;;;;;
	("^!amazon:? +\\(.*\\)" . ;; Amazon
	"http://www.amazon.com/s/?&field-keywords=\\1" )
	("^!imdb:? +\\(.*\\)" . ;; IMDB
	"http://www.imdb.com/find?s=all&q=\\1" )
        ("^!tmdb:? +\\(.*\\)" . ;; The Movie Database
	"http://www.themoviedb.org/search?search=\\1")
        ;; Add Later

	))

#+end_src
