#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Deerpig's dot emacs
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/deerpig/dot-emacs/index.org
  :Created: 2017-02-12T11:39@Prek Leap (11.642600N-104.919210W)
  :ID: e22cd45b-0e72-4b0f-ba1b-a0d4c4d3c90f
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

I've been threatening to convert my emacs init into literate
org-mode.  This is where all the damage will be available for all the
world to see.

The proper way of doing this is to evaluate all the elisp blocks when
starting emacs.  However, I don't expect to be able to do this for
quite some time.  I have a loooooooong ways to go before I'll have
everything moved over.

So for now, I will be tangling each file that I convert to org-mode
and export the elisp to a file that can be read by my existing init
setup.  When everything is finished I will switch over to doing things
/the right way/.

Feedback Is Welcome!

* Table of Contexts
 
 - dot.emacs
 - [[./dot-packages.org][Packages]]
 - Helm
 - Mu4e
 - [[./dot-hydra.org][Hydra Config]]


